name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21" # Or the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Make sure this matches your build directory

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Update Repository Description with URL
        env:
          REPO_URL: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        run: |
          gh repo edit --description "Deployed at $REPO_URL"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
